### ISSUE TITLE
It seems that the easy way to install the ARM toolchain is not works.

### ISSUE THREAD

**Issue by AlfordHongkong** [gnu-mcu-eclipse/arm-none-eabi-gcc#1]
I can't install ARM toolchain after input the command 
$ xpm install @gnu-mcu-eclipse/arm-none-eabi-gcc --global

It stuck at:
Downloading https://github.com/gnu-mcu-eclipse/arm-none-eabi-gcc/releases/download/v7.2.1-1.1/gnu-mcu-eclipse-arm-none-eabi-gcc-7.2.1-1.1-20180401-0515-osx.tgz...

or shows error as below:
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ETIMEDOUT 52.216.64.224:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

My OS version is macOS high sierra 10.13.4. 

I don't know what's going on and  just post it to let you know. I'm gonna  try another way to install the toolchain.

**Comment by ilg-ul** [comment]
Is your internet access unrestricted? 

Please try a 

```
curl -L https://github.com/gnu-mcu-eclipse/arm-none-eabi-gcc/releases/download/v7.2.1-1.1/gnu-mcu-eclipse-arm-none-eabi-gcc-7.2.1-1.1-20180401-0515-osx.tgz
```

If you need to configure proxies, or other such mechanisms, it'll probably not work.
