### ISSUE TITLE
Running arm-none-eabi-gcc-ar.exe fails to find liblto_plugin-0.dll

### ISSUE THREAD

**Issue by oallaire** [gnu-mcu-eclipse/arm-none-eabi-gcc#2]
Windows 10 64 bits pro with arm-none-eabi-gcc installed manually to version 7.2.1-1.1-20180401-0515.

Here is the exact error:
`
C:\Users\olivi\Documents\base-board\app\build-debug>"C:\Users\olivi\AppData\Roaming\GNU MCU Eclipse\ARM Embedded GCC\7.2.1-1.1-20180401-0515\bin\arm-none-eabi-gcc-ar.exe"
C:\Users\olivi\AppData\Roaming\GNU MCU Eclipse\ARM Embedded GCC\7.2.1-1.1-20180401-0515\bin\arm-none-eabi-gcc-ar.exe: Cannot find plugin 'liblto_plugin-0.dll'
`
There is a DLL at this location:
`C:\Users\olivi\AppData\Roaming\GNU MCU Eclipse\ARM Embedded GCC\7.2.1-1.1-20180401-0515\lib\gcc\arm-none-eabi\7.2.1`

However, MinGW does have a dll called liblto_plugin-0.dll.

Note that I also have the an old version of GNU Tools ARM Embedded (5.2 2015q4) and the archiver works for this one.

Anything I should try to fix this?

**Comment by oallaire** [comment]
I just re-examined the structure and noticed I did not try the archiver located at C:\Users\olivi\AppData\Roaming\GNU MCU Eclipse\ARM Embedded GCC\7.2.1-1.1-20180401-0515\arm-none-eabi\bin\ar.

This one works. But I liked the idea of having an archiver with a name that can be located in my PATH and not be mistaken with all the other archivers called ar.

**Comment by ilg-ul** [comment]
I cannot confirm this, starting `arm-none-eabi-ar.exe` on my Win 10 x64 VM is ok: 

```
C:\Users\ilg>C:\Users\ilg\AppData\Roaming\xPacks\@gnu-mcu-eclipse\arm-none-eabi-gcc\7.2.1-1.1.3\.content\bin\arm-none-eabi-ar.exe --version
GNU ar (GNU MCU Eclipse ARM Embedded GCC, 64-bits) 2.29.51.20171128
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

Please be sure you are using the latest release, and that you have a clean PATH.

**Comment by oallaire** [comment]
My path is definitely problematic. So the bug must be on my side.

It's just confusing that arm-none-eabi-ar.exe does not have the same behavior as C:\Users\olivi\AppData\Roaming\GNU MCU Eclipse\ARM Embedded GCC\7.2.1-1.1-20180401-0515\arm-none-eabi\bin\ar when there are path problems. Since I must keep my Path env the same, I use the fully qualified path of ar for now.

Thanks for the help.

**Comment by ilg-ul** [comment]
If you read the documentation pages, you'll see many explicit recommandations to avoid adding toolchains to the system path. Now you'll probably understand the reason for this.

The same applies to mingw/cygwin and other such oddities.
