### ISSUE TITLE
When will there be a GCC 8.2 Release?

### ISSUE THREAD

**Issue by SeppyMoose** [gnu-mcu-eclipse/arm-none-eabi-gcc#3]
Hello,

Wasn't sure where to post this so I suppose here is the right place. 
GCC had some major issues with fold expressions involving lambdas, these issues were resolved in 8.2.

Is there anything I can do to help get 8.2 out the door faster?

Kind Regards,
     David Ledger

**Comment by ilg-ul** [comment]
GNU MCU Eclipse ARM Embedded GCC releases follow ARM releases:

https://launchpad.net/gcc-arm-embedded/+series

8.2 will probably be available by the end of the year.
