### ISSUE TITLE
Python3 support in GDB

### ISSUE THREAD

**Issue by Novakov** [gnu-mcu-eclipse/arm-none-eabi-gcc#5]
GDB included in toolchain package is compiled with Python 2 support. It would be nice to enable support for Python 3 as support for 2.7 is ending next year. 

I don't know if I should raise this issue here or in arm-none-eabi-gcc-build repository. If in the -build one, let me know I will create issue there.

**Comment by ilg-ul** [comment]
Please add a ticket to the -build repo.

**Comment by Novakov** [comment]
Done.
